### ISSUE TITLE
retryCount is always being incremented so polling stops after retryLimit times

### ISSUE THREAD

**Issue by scottkidder** [mtoygar/ember-poller#7]

**Comment by scottkidder** [comment]
Maybe my use case is a bit different from the original design. I'd like to be able to poll my task indefinitely. Maybe even tolerating or 'restarting' the poll if there happen to be failures.

**Comment by scottkidder** [comment]
For now I'm just setting a very high retryLimit and this works great as a stop-gap. I wonder if there is room for my above use case in this addon though?

Thanks for the great addon, very clean and the tests look great! :+1:

**Comment by mtoygar** [comment]
Thanks for the kind comments @scottkidder. I can add a flag to options for this purpose. I will let you know, sorry for late response.

**Comment by mtoygar** [comment]
hi again @scottkidder. I think over the flag solution and decided that adding a flag will unnecessarily increase the code complexity. However, I have a suggested solution for you. If you specify `retryLimit` as `Infinity` or `Number.POSITIVE_INFINITY`, polling should last forever.

**Comment by scottkidder** [comment]
Thanks @mtoygar
