### ISSUE TITLE
Feature request: ability to pass pollTask arguments

### ISSUE THREAD

**Issue by andrewfan** [mtoygar/ember-poller#8]

**Comment by mtoygar** [comment]
why do u need such a feature @andrewfan ?

It actually makes total sense when you think but I cannot come up with a proper use case. Can you describe your case.

**Comment by mtoygar** [comment]
Now I also encounter with such a case, I will add this feature probably in this week

**Comment by mtoygar** [comment]
@andrewfan I have published 1.0.0 version and what you propose is also handled in this version.
